version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi:/app
      - ./secrets/hooptuberdev.json:/app/hooptuberdev.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/hooptuberdev.json
    env_file: # pulling env variables
      - .env

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./worker:/app
      - ./secrets/hooptuberdev.json:/app/hooptuberdev.json:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/hooptuberdev.json
    env_file:  # pulling env fariables
      - .env
