services:
  - type: web
    name: hooptuber-client
    env: docker
    repo: https://github.com/ceeeeeeek/HoopTuber
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: free

  - type: web
    name: hooptuber-fastapi
    env: docker
    repo: https://github.com/ceeeeeeek/HoopTuber
    dockerfilePath: ./fastapi/dockerfile
    dockerContext: ./fastapi
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/hooptuberdev.json
      # - key: GOOGLE_APPLICATION_CREDENTIALS
      #   value: /app/hooptuberdev.json # ONLY USING FOR LOCAL TESTING WITH DOCKER
  - type: worker
    name: hooptuber-worker
    env: docker
    repo: https://github.com/ceeeeeeek/HoopTuber
    dockerfilePath: ./worker/Dockerfile
    dockerContext: ./worker
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/hooptuberdev.json
    